language: common-lisp
sudo: required

# The following addon is to get the last builds working.
addons:
  chrome: stable

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    # ABCL throws a stack overflow. Which is weird, but hard to debug.
    - env: LISP=abcl
    # Allegro is failing with some device error
    - env: LISP=allegro
    # CMUCL is failing with "Can't open /home/travis/.com/..."
    - env: LISP=cmucl

install:
  - curl -L https://github.com/erwinvaneijk/cl-travis/raw/master/install.sh | sh

script:
  #  - cl -l prove -e '(unless (prove:run :fibonacci-tests))
  #                          (uiop:quit 1))'
  - cl -l rove -e '(ql:quickload :function-cache)(asdf:test-system :fibonacci)'
