language: lisp
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl-bin
    - LISP=sbcl32
    - LISP=ccl-bin
    - LISP=ccl32-bin
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

# matrix:
#   allow_failures:
#     - env: LISP=ecl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install prove

script:
  - run-prove fibonacci-tests.asd