language: common-lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    - LISP=sbcl32
    - LISP=clisp32
    - LISP=cmucl

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  #  - cl -l prove -e '(unless (prove:run :fibonacci-tests))
  #                          (uiop:quit 1))'
  - cl -l rove -e '(asdf:test-system :fibonacci-tests)'
